### ISSUE TITLE
ndef applet needs adjustment to AIDs

### ISSUE THREAD

**Issue by amalg** [DangerousThings/flexsecure-applets#1]
Apparently the maintainer of the NDEF applet made some decisions. The source should be adjusted and recompiled so it uses the correct AID and package IDs;

https://github.com/OpenJavaCard/openjavacard-ndef/issues/10

Amal

**Comment by StarGate01** [comment]
The AID of the instance is specified at install time and differs from the default AID encoded in the cap file, see https://github.com/StarGate01/flexsecure-applets/blob/master/docs/applets/4-ndef.md#installing-the-applet . 

Do you need the AIDs to be identical? (Fidesmo..)

**Comment by StarGate01** [comment]
Changed in 149a311835b16792a5d4e5a23585c2ed0c04218b .
